### ISSUE TITLE
Styelsheet URL breaks when moving up in the directory "../"

### ISSUE THREAD

**Issue by julienetie** [addyosmani/critical#95] opened 2015-07-18 13:57 UTC
This:

```
     background: url('../folder/image.jpg');
```

becomes:

```
     background: url('folder/image.jpg');
```

It's not always convenient when taking src from a different directory (unless I'm doing something wrong) The same applies for multiple traversing. I found this but I'm not sure if the change will break anything:

lib/inline-styles.js

```
function rebaseRelativePaths(basePath, cssPath, cssStr) {
..//
                    for (var k = 0; k < pathDiff; k++) {
                        newPath = newPath.replace('../', '');
                    }
//..
}
```

Maybe remove the back tracking of dir could be better as an option.

**Comment by bezoerb** [comment] 2015-07-18 21:09
@julienetie could you provide some more information about your setup?

**Comment by julienetie** [comment] 2015-07-19 20:52
Sure:

So this is the css src 
```
    background: #222 url('../funny-how.jpg') repeat-y;
```
which critical outputs into the html as:
```
    background: #222 url('funny-how.jpg') repeat-y;
```
gulpfile.js
```
gulp.task('build-404-critical-css', ['build-404-css'], function() {
    return critical.generateInline({
        base: './',
        src: './src/html/404.html',
        css: ['./style/404.min.css'],
        htmlTarget: './404/index.php',
        exclude: true,
        width: 1366,
        height: 4000,
        minify: true
    });
});
```

**Comment by bezoerb** [comment] 2015-07-19 21:55
@julienetie i've made some tests but i couldn't reproduce your issue.
The background-image in the critical css always resolves to `url('/funny-how.jpg')`

Which version of critical are using?

**Comment by bezoerb** [comment] 2015-07-19 21:57
You also could use the [`stream`](https://github.com/addyosmani/critical#gulp) method when using with gulp.

**Comment by julienetie** [comment] 2015-07-26 11:54
Thanks @bezoerb, I'll give it a try.

**Comment by bezoerb** [comment] 2015-08-06 21:11
@julienetie any updates on this one?

**Comment by SerzN1** [comment] 2015-11-13 16:10
You must use option
`pathPrefix: '/' + yourPath`
Your code will be immediately on the page.

**Comment by bezoerb** [comment] 2016-02-04 17:00
We've made some progress on this topic @julienetie. The asset paths inside the critical css should now stay relative in case they were relative the first place. Could you check if your issue is fixed in the `vinyl` branch?
 ```
npm install --save-dev git+https://github.com/addyosmani/critical.git#vinyl
```
/cc @SerzN1

**Comment by bezoerb** [comment] 2017-07-01 22:21
Closing this due to lack of feedback. Feel free to reopen if you still got problems on this one.

**Closed by bezoerb** 2017-07-01 22:21 UTC
