### ISSUE TITLE
Relative paths from absolutely linked CSS

### ISSUE THREAD

**Issue by hom3chuk** [addyosmani/critical#216] opened 2017-06-21 14:03 UTC
## Steps to reproduce

1. In HTML, link to a CSS with absolute path `http://example.com/some/deep/dir/style.css`
2. In CSS refer `@font-face` `src` one directory up `url(../fonts/font.eot)`
3. Critical CSS gets `url(../fonts/font.eot)`, not expected `url(http://example.com/some/deep/fonts/font.eot)`

## Demo

Made a demo for this one:

- [repo](https://github.com/hom3chuk/furry-octo-succotash)
- [GH pages](https://github.com/hom3chuk/furry-octo-succotash)

gulpfile:
```
var gulp = require('gulp'),
    critical = require('critical');


gulp.task('css', function(){
    return critical.generate({
        base: './',
        src: 'https://hom3chuk.github.io/furry-octo-succotash/',
        dest: './critical.css',
        extract: false,
        width: 2560,
        height: 1440,
        timeout: 300000,
        minify: false,
        renderWaitTime: 5000,
        blockJSRequests: false,
        ignore: []
    });
});

gulp.task('default', ['css']);
```

## Expected `critical.css` contents:
```
@font-face {
  font-family: FontAwesome;
  src: url(https://hom3chuk.github.io/furry-octo-succotash/styles/some/deep/fonts/fontawesome-webfont.eot?v=4.7.0);
  src: url(https://hom3chuk.github.io/furry-octo-succotash/styles/some/deep/fonts/fontawesome-webfont.eot?#iefix&v=4.7.0)
    format('embedded-opentype'),
    url(https://hom3chuk.github.io/furry-octo-succotash/styles/some/deep/fonts/fontawesome-webfont.woff2?v=4.7.0)
    format('woff2'),
    url(https://hom3chuk.github.io/furry-octo-succotash/styles/some/deep/fonts/fontawesome-webfont.woff?v=4.7.0) format('woff'),
    url(https://hom3chuk.github.io/furry-octo-succotash/styles/some/deep/fonts/fontawesome-webfont.ttf?v=4.7.0) format('truetype'),
    url(https://hom3chuk.github.io/furry-octo-succotash/styles/some/deep/fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular) format('svg');
  font-weight: 400;
  font-style: normal;
}

.test-header {
  font-family: FontAwesome;
}
```

## Actual `critical.css` contents:
```
@font-face {
  font-family: FontAwesome;
  src: url(../fonts/fontawesome-webfont.eot?v=4.7.0);
  src: url(../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0)
    format('embedded-opentype'),
    url(../fonts/fontawesome-webfont.woff2?v=4.7.0)
    format('woff2'),
    url(../fonts/fontawesome-webfont.woff?v=4.7.0) format('woff'),
    url(../fonts/fontawesome-webfont.ttf?v=4.7.0) format('truetype'),
    url(../fonts/fontawesome-webfont.svg?v=4.7.0#fontawesomeregular) format('svg');
  font-weight: 400;
  font-style: normal;
}

.test-header {
  font-family: FontAwesome;
}
```
Which, when inlined at `index.html`, break fonts URLs (see [index-with-critical.html](https://hom3chuk.github.io/furry-octo-succotash/index-with-critical.html)).

**Comment by josenobile** [comment] 2017-08-24 14:00
I'm affected too. This bug is related to critical, penthouse or phantomjs? I want to fix it.

**Comment by pocketjoso** [comment] 2017-08-24 14:09
`critical`. Penthouse doesn't change any paths as it just receives css content without any file paths. https://criticalcss.com however (my paid service on top of penthouse) resolves paths correctly. :)

But yeah this must just be some bug in critical that hopefully shouldn't be too hard to fix - I have no insight into this code however.

**Comment by futureweb** [comment] 2018-02-28 10:44
any news on this? ;-)

**Comment by mintymatt** [comment] 2018-08-30 11:31
Still an issue, any more news on this? :)

**Comment by bezoerb** [comment] 2018-08-31 09:36
@mintymatt: I'm currently working on a rewrite of critical.

**Comment by pocketjoso** [comment] 2018-08-31 09:47
@bezoerb cool! I think it would be great if we could discuss this together, to make sure Penthouse is used as efficiently as possible, and also to discover any potential changes in Penthouse that would help you. Can you send me an email, or DM on twitter (@pocketjoso)?

**Comment by bezoerb** [comment] 2018-08-31 10:14
@pocketjoso thanks :)
I hope to have some spare time for this next week. I'll ping you as soon as i'm ready to move on with the rewrite

**Comment by AT41** [comment] 2019-07-24 16:54
Hi, was this ever resolved fully? Critical replaces `../` with `../../../private/var/folders/...` when I use an absolutely linked css.

**Comment by AT41** [comment] 2019-07-24 17:27
Hi, was this ever resolved completely? My absolute css contains relative paths that get rewritten to /private/var/folders/....

**Comment by bezoerb** [comment] 2019-07-28 22:03
@AT41: Can you post your config or a gist to reproduce the error?

**Comment by AT41** [comment] 2019-08-01 14:47
Sorry for the wait! Here's a reproduction of the bug: https://gitlab.com/anthonytang411/temp-critical-repro

**Comment by AT41** [comment] 2019-08-02 18:07
Oh, I think it's because my version of Critical is just horribly out of date. It's completely fixed for me now

**Comment by bezoerb** [comment] 2019-08-04 21:25
@AT41: that sounds great :)
Closing this issue now. Feel free to reopen if it pops up again.

**Closed by bezoerb** 2019-08-04 21:25 UTC
Labels: bug, enhancement
