### ISSUE TITLE
Uncritical is breaking because of the `inline-critical` package

### ISSUE THREAD

**Issue by rohanvakharia** [addyosmani/critical#374] opened 2019-06-02 09:20 UTC
While generating the critical, html and uncritical, I have set rebase to false because there are some errors in the CSS.
Though `inline-criticalcss` also has `postcss-url` dependency and I do not see any option to disable the that which causes uncritical to break.

Do you have any solution to that?

Related version : `critical@next`

**Comment by bezoerb** [comment] 2019-06-02 09:40
Hey, can you share some more insights like your confic or anything that helps reproducing the issue?

**Comment by rohanvakharia** [comment] 2019-06-02 16:56
Here is my config:

```
var critical = require('critical');

critical.generate({
    base: 'dist/',
    src: 'https://<domainname>/',
    width: 1300,
    height: 900,
    target: {css: 'critical.css' , html: 'index-critical.html' , uncritical: 'uncritical.css'},
    minify: true,
    extract: true,
    rebase: false,
});
```

**Comment by rohanvakharia** [comment] 2019-06-08 15:11
@bezoerb any update?

**Comment by bezoerb** [comment] 2019-06-08 20:24
Can you also share the css file? The error looks like there's something wrong with the css. There are some cases in which we need to use postcss like for example rebase or extract ... 
The [`CssSyntaxError`](https://api.postcss.org/CssSyntaxError.html) thrown by postcss is caused by an error in the css. If you could share the file or the link to the html ('https://<domainname>/') i can help debugging ;)

**Comment by rohanvakharia** [comment] 2019-06-11 06:47
I am using WordPress and related plugins. In that plugin there is a semicolon missing for CSS property.
I cannot control the plugin.

**Comment by bezoerb** [comment] 2019-06-11 08:58
In this case you might need to disable all features which rely on postcss or add some quickfix to add the missing semicolon to the malformed css before passing it to critical.

**Comment by bezoerb** [comment] 2019-06-11 08:59
Is there a github repo for the WP Plugin? We can also try to open up a PR to get this fixed on the plugin side

**Comment by rohanvakharia** [comment] 2019-06-11 11:47
Sorry, it is premium plugin

**Comment by bezoerb** [comment] 2019-09-15 20:52
Closing this as the error isn't caused by critical. We can't fix syntax errors in css. This needs to be solved upstream.

**Closed by bezoerb** 2019-09-15 20:52 UTC

**Comment by creatifyteam** [comment] 2021-03-01 08:28
why not we pass that css file? I mean why we do an exception error and stop the process? we can handle the error and show it and continue the process
