### ISSUE TITLE
File not found issue when concurrency > 1

### ISSUE THREAD

**Issue by phaistonian** [addyosmani/critical#341] opened 2018-11-27 06:16 UTC
When setting `concurrency` to > 1  then errors such as the one below are rising.

Temp folders/files are removed too early - it seems.

```
Error: net::ERR_FILE_NOT_FOUND at file:///private/var/folders/ml/vsjp5d_j19zf06rpg91g30dh0000gp/T/7ac6ca0696e3984b4fd19db1fd5beeb8/temp-index.html
```

**Comment by bezoerb** [comment] 2018-11-27 06:18
Thanks for testing @phaistonian

**Comment by bezoerb** [comment] 2018-11-27 15:58
@phaistonian: i'm not able to reproduce the error. Can you explain your setup/config or add a testcase?

**Comment by phaistonian** [comment] 2018-11-27 16:01
@bezoerb  I am afraid it's quite complex - the whole process - to get it down to a sharable example.

Here's the config though:

```js
  const res = await critical.generate({
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36',
    minify: true,
    extract: false,
    inline: false,
    dimensions,
    html,
    ignore,
    // concurrency: 1,
    user: AUTH_USERNAME,
    pass: AUTH_PASSWORD,

    // https://github.com/addyosmani/critical/blob/master/CHANGELOG.md#v200--2018-11-27
    penthouse: {
      timeout: 360000,
      include,
    },
  });
```

My theory is that, because I am running multiple `critical.generate` in a loop, somehow the temp files are removed before they are used.

**Comment by bezoerb** [comment] 2018-11-27 16:03
Thanks :)
I'll check the loop thing

**Comment by bezoerb** [comment] 2018-11-27 22:43
@phaistonian: i just published a new prerelease version. The error should be fixed now. Would you mind checking again?

**Comment by phaistonian** [comment] 2018-11-28 08:12
Works like a charm :)

Thank you.

**Comment by phaistonian** [comment] 2018-11-28 09:37
oh while - there, you might want to fix this too.

![image](https://user-images.githubusercontent.com/796530/49142659-02f69a00-f302-11e8-913a-8f075800f113.png)

`rebase` can also be a function.

**Comment by bezoerb** [comment] 2018-11-28 15:34
Thanks @phaistonian!
https://github.com/addyosmani/critical/pull/342 is merged :)

**Closed** 2018-11-28 15:37 UTC
