### ISSUE TITLE
Unhandled rejection TypeError: Bad argument - phantomJsBinPath is always null

### ISSUE THREAD

**Issue by gCardinal** [addyosmani/critical#190] opened 2017-02-08 21:37 UTC
Information on the packages installed:

- critical: 0.8.1
- penthouse: 0.10.9
- phantomjs-prebuilt: 2.1.14
- Installed with yarn

Simple code I'm trying to run:

```js
var critical = require('critical')

critical.generate({
    inline: true,
    src: 'index.html',
})
```

Error I get:

```
Unhandled rejection TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:339:9)
    at generateCriticalCss (/var/www/html/node_modules/penthouse/lib/index.js:103:10)
    at process._tickCallback (node.js:377:9)
```

I isolated the problem (or at least, a first step in figuring out what's wrong) to `lib/index.js` line 102 in penthouse. The variable `phantomJsBinPath` is null. Looking into `phantomjs-prebuilt`, they export the variable only if this sample does not error:

```js
try {
  var location = require('./location')
  exports.path = path.resolve(__dirname, location.location)
  exports.platform = location.platform
  exports.arch = location.arch
} catch(e) {
  // Must be running inside install script.
  exports.path = null
}
```

I have no `./location` directory so this fails.

All I did was a `yarn add critical` and then I encountered this problem. Am I missing an install step or is this a bug with yarn?

**Comment by joaogarin** [comment] 2017-02-27 12:10
Currently having the same issue, where you able to find out the problem?

**Comment by gCardinal** [comment] 2017-02-27 20:07
No, I tried to figure it out some more after I posted this, but couldn't find the solution. I also don't know those libraries very well so it's difficult for me to figure out what causes the issue.

**Comment by connor-baer** [comment] 2017-04-14 18:34
I just ran into the same issue and found a solution. @gCardinal, your investigation pointed me into the right direction. Thank you!

The problem is that - for whatever reason - `Phantom` wasn't actually installed by `phantomjs-prebuilt`. The `phantom` folder and the `location.js` file are missing in the `lib` folder. You can fix this by running...

`npm install phantomjs-prebuilt --phantomjs_cdnurl=https://bitbucket.org/ariya/phantomjs/downloads`

...as stated in the `phantomjs-prebuilt` [documentation](https://www.npmjs.com/package/phantomjs-prebuilt#downloading-from-a-custom-url).

**Comment by bezoerb** [comment] 2017-07-12 22:09
Closing this as it seems that this is not an issue with `critical` itself. Feel free to reopen if you need further assistance on this.

**Closed by bezoerb** 2017-07-12 22:09 UTC
