### ISSUE TITLE
CriticalCssWebpackPluginTypeError: Cannot read property 'content-type' of undefined

### ISSUE THREAD

**Issue by TomDeSmet** [addyosmani/critical#414] opened 2019-11-04 16:02 UTC
I'm trying to build a project on a new MacBook (Catalina) which builds fine on my old MacBook (Mojave). Nothing changed in packages, just a minor version in node.js (v12.12.0 instead of v12.10.0 on the old MacBook).

I get this error:
```
99% [0] after emitting CriticalCssWebpackPluginTypeError: Cannot read property 'content-type' of undefined
    at temp (/Users/tom/Sites/parkwind-oriel-dev/node_modules/critical/lib/file-helper.js:106:37)
    at /Users/tom/Sites/parkwind-oriel-dev/node_modules/critical/lib/file-helper.js:204:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Other projects with the same setup are being build and the Critical CSS files are being generated. I tried updating the NPM modules to the same versions as the working project, but no cigar. Updating them to the very latest didn't work either.
And I can't seem to find anything related on Google.

Does anyone have an idea what this could be?

**Comment by DandeSuen** [comment] 2019-12-03 03:57
Me too.
`[11:40:00] -> Generating critical CSS: http://estaging.avepoint.com/try -> web-elements/cpassets/compiled/css/try_critical.min.1575344391678.css
[11:40:00] TypeError: Cannot read property 'content-type' of undefined
    at temp (/home/avepoint/docker-share/www/craft3/node_modules/critical/lib/file-helper.js:107:37)
    at requestAsync.then.response (/home/avepoint/docker-share/www/craft3/node_modules/critical/lib/file-helper.js:204:64)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

And I find param "src" is wrong. You could be print the param "src" to console log. Take closer look at, Because every projects hostname is different.

**Comment by michtio** [comment] 2020-01-09 08:22
I'm running into the same issue, are there any solutions or suggestions for this?

`99% [0] after emitting CriticalCssWebpackPluginTypeError: Cannot read property 'content-type' of undefined
    at temp (/home/forge/sandbox.educationendowmentfoundation.org.uk/node_modules/critical/lib/file-helper.js:107:37)
    at requestAsync.then.response (/home/forge/sandbox.educationendowmentfoundation.org.uk/node_modules/critical/lib/file-helper.js:205:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by bezoerb** [comment] 2020-01-09 12:54
Could someone provide a sample project to reproduce the error?

**Comment by michtio** [comment] 2020-01-10 12:22
@bezoerb I did some further research yesterday and I found the following:

```
production: "https://domain.com",
local: () => process.env.DEFAULT_SITE_URL || "https://domain.test",
critical: process.env.DEFAULT_SITE_URL,
publicPath: () => process.env.PUBLIC_PATH || "/dist/",
```

Notice my publicPath, so I'm loading the value in from my environment file, just in case the environment file doesn't have a `DEFAULT_SITE_URL` set I had my critical path with the arrow function as seen above in the publicPath and local. 

When `() => process.env.DEFAULT_SITE_URL || "https://domain.test",` is used as the value ( so the arrow function ) and printing the src, it will show that CriticalSrcPath will actually be `() => process.env.DEFAULT_SITE_URL || "https://domain.test",` and not the `DEFAULT_SITE_URL` or `https://domain.test` when no default site url is found.

That's my case, I don't know if you can add handling of arrow functions into critical? But it would be nice.

Thank you!

If you want me to send over my webpack config, with the working and non-working one, please let me know.

**Comment by khalwat** [comment] 2020-09-16 22:51
This happens if the `src` URL that you pass in isn't valid or returns no response.

I think this is something that critical should be handling more gracefully, though. I'd love to see the aforementioned PR merged in.

**Comment by khalwat** [comment] 2020-09-16 23:04
Ah, looks like this might be addressed in Critical 2.0.x -- I will test and report back

**Comment by khalwat** [comment] 2021-02-05 15:31
I never reported back. It does address the issue

**Comment by bezoerb** [comment] 2021-02-27 22:21
Thanks @khalwat :)
Looks like i can close this one

**Closed by bezoerb** 2021-02-27 22:21 UTC
