### ISSUE TITLE
"File not found" after upgrading to v2.0.0-18

### ISSUE THREAD

**Issue by evemontalvao** [addyosmani/critical#377] opened 2019-06-13 16:23 UTC
Alter upgrade to v2, following [this](https://github.com/addyosmani/critical/issues/360) recommendation, I'm getting the following error, but the path is correct, I'm able to access the same path through `cd` or `cat`, so this doesn't seem to be the problem.
```
Error: Error: file "/static/css/views/profile/index.css" not found in "/Users/evellynmontalvao/projects/tanya/dev/static/css/views". Specify base path.
    at links.map.link (/Users/evellynmontalvao/projects/tanya/node_modules/inline-critical/index.js:141:17)
    at Array.map (<anonymous>)
    at inline (/Users/evellynmontalvao/projects/tanya/node_modules/inline-critical/index.js:129:11)
    at create (/Users/evellynmontalvao/projects/tanya/node_modules/critical/src/core.js:220:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

This is my file structure:
![Screen Shot 2019-06-13 at 13 20 13](https://user-images.githubusercontent.com/5607300/59449722-01904900-8dde-11e9-8f33-5e7cfb0c58d1.png)

And this is the code:
```
  Object.keys(examplePaths).map(async (key) => {
    const { css, html, uncritical } = await critical.generate({
      inline: true,
      base: `${rootPath}/dev/static/css/views`;,
      src: `${baseUrl}${examplePaths[key]}`,
      css: [`/${key}/index.css`],
      dimensions: [
        {
          width: 420,
        },
        {
          width: 768,
        },
        {
          width: 960,
        },
        {
          width: 1200,
        },
      ],
      minify: true,
      extract: true,
    });
```
Can someone please help me with this?

**Comment by bezoerb** [comment] 2019-06-13 16:55
You’re passing an absolute path for the css (leading slash). This is why critical doesn’t find the file. You could try using a relative path:  ```
css: [`${key}/index.css`],
```

**Comment by bezoerb** [comment] 2019-06-13 16:57
I will try to make this a bit less error prone

**Comment by evemontalvao** [comment] 2019-06-13 17:10
> You’re passing an absolute path for the css (leading slash). This is why critical doesn’t find the file. You could try using a relative path:
> 
> ```
> css: [`${key}/index.css`],
> ```

I've tried this and I'm still getting the same error :/

**Comment by bezoerb** [comment] 2019-06-13 17:12
Sorry to hear that. I’ll take a look this evening and see if I can reproduce/fix this

**Comment by evemontalvao** [comment] 2019-06-13 17:12
@bezoerb Thank you, let me know if you need more information

**Comment by bezoerb** [comment] 2019-06-15 21:50
Hey @evemontalvao, i think i found the problem. The `base` option should represent the docroot of your project so we can locate the referenced files. According to the error log you have an absolute referenced stylesheet in your html (`/static/css/views/profile/index.css`).
When using the `extract` option without specifying `target: {uncritical: <path to uncritical.css>}`, [`inline-critical`](https://github.com/bezoerb/inline-critical) creates a copy of all css files linked in the html document and removes the critical css. We look for the files with `base` option used as docroot. 

**base:** `${rootPath}/dev/static/css/views`
**styesheet:** `/static/css/views/profile/index.css`

So inline critical tries to remove the critical styles from `${rootPath}/dev/static/css/views/static/css/views/profile/index.css` where it couldn't find the file.

You can try changing your config like this:
```js
    const { css, html, uncritical } = await critical.generate({
      inline: true,
      base: `${rootPath}/dev`,
      src: `${baseUrl}${examplePaths[key]}`,
      css: [`/static/css/views/${key}/index.css`],
      dimensions: [
        {
          width: 420,
        },
        {
          width: 768,
        },
        {
          width: 960,
        },
        {
          width: 1200,
        },
      ],
      minify: true,
      extract: true,
    });
``` 

or it should even be possible to drop `base` & `css` options and let critical try to assume the paths automatically.

**Comment by XhmikosR** [comment] 2019-08-07 05:54
Closing due to lack of reply.

**Closed by XhmikosR** 2019-08-07 05:54 UTC
