### ISSUE TITLE
Generated CSS is big

### ISSUE THREAD

**Issue by vardanabhanot** [addyosmani/critical#555] opened 2023-02-22 15:01 UTC
So I tried to generate critical CSS, but the CSS is like 30,000 characters big. And I tested it with css-tricks.com and it was giving error.
the error I am getting with css-tricks.com is
`/index.html.css:2:4: Unknown word`

And the configuration I am using is
`generate({
        base: "critical_css/" + basename,
	src: url,
	target: {
		css: "critical.css",
	},
	width: 1300,
	height: 900,
	extract: true,
});`

Do I need to do something in the config to make it work?
And it is also including inlined CSS too

**Comment by bezoerb** [comment] 2023-03-01 19:02
Hey, thanks for using critical:-)
The config looks fine to me... can you post a link to the project or is it private? Otherwise an example which makes it possible to reproduce the issue would be helpful

**Comment by vardanabhanot** [comment] 2023-03-03 09:03
Hello,

Just use the above config, as I was just using that and nothing more. And try it on css-tricks.com first, you will be able to reproduce that.
As I later tried to use penthouse directly and everything was working fine in it, so the issue is most probably in the style linter

**Comment by bezoerb** [comment] 2023-04-09 22:25
Hey @vardanabhanot,

i tried with css-tricks and i got the same error. The error is caused by an invalid inlined stylesheet 
<img width="788" alt="image" src="https://user-images.githubusercontent.com/1697800/230799309-c5aa7fd2-859e-448e-9120-0785bac13ed7.png">

This is fixed in the linked PR.
Regarding the Big resulting critical css i would need to take a look at the original files to debug this

**Comment by bezoerb** [comment] 2023-04-09 22:33
Would you test again using the latest version [v5.1.0](https://github.com/addyosmani/critical/releases/tag/v5.1.0)

**Comment by onlinebizsoft** [comment] 2023-06-09 11:03
Look like the tool includes all declaration (even overwritten ones) for every element in the above-the-fold area.
For example we have an element and it has multiple font declaration applied so only one is active and get used but look like all applicable rules will be included

**Comment by bezoerb** [comment] 2023-09-15 22:35
@onlinebizsoft could you try again with [v5.2.0](https://github.com/addyosmani/critical/releases/tag/v5.2.0)
I added an option to customize cleancss. See https://github.com/clean-css/clean-css#optimization-levels

**Comment by bezoerb** [comment] 2024-01-27 23:27
I'm closing this due to lack of feedback.
Feel free to reopen if there are new insights

**Closed by bezoerb** 2024-01-27 23:27 UTC
Labels: awaiting reply

**Comment by onlinebizsoft** [comment] 2024-01-28 12:44
Sorry I missed the new option. Let me check and get back when I have the result.
