### ISSUE TITLE
Error when using local url as source

### ISSUE THREAD

**Issue by mikeebee** [addyosmani/critical#130] opened 2016-04-21 00:16 UTC
Using a HTML file url works great, so does a remote url. But when I try to use a local url through MAMP, I get this error...

`Unhandled rejection Wrong status code 403 for [object Object]`

Any ideas?

Using via npm and Gulp
v.0.7.2

Here is my code...

```
var critical = require('critical');

gulp.task('critical', function(cb) {
    critical.generate({
        base: './',
        src: 'http://localurl.dev',
        css: ['css/styles.css'],
        dimensions: [{
            width: 320,
            height: 480
        }, {
            width: 768,
            height: 1024
        }, {
            width: 1280,
            height: 960
        }],
        dest: '_templates/default_site/_embeds/critical_css_home.html',
        extract: false,
        include: ['.c-slideshow, .c-more-to-see, .c-slideshow-gallery__container, .c-loader, .c-slideshow--hero'],
        exclude: ['@font-face']
    });
});
```

Let me know if you need more information.

Thanks!

**Comment by miralize** [comment] 2016-05-05 09:34
Experiencing the same issue. Gulp 3.9.1 & Node v6

**Comment by bezoerb** [comment] 2016-05-07 21:20
just tried `the cli with some local url and it worked just as expected. Is there some sort of authentication required? What's the output when you just try to fetch the url using `wget` or `curl`?

**Comment by miralize** [comment] 2016-05-07 21:26
Trying ` node_modules/.bin/critical http://dev.lovindublin.com/ -m`

   ```Error: Wrong status code 403 for [object Object]
   Usage: critical <input> [<option>]```

cURL `curl http://dev.lovindublin.com/`

`
Header
HTTP/1.1 200 OK
Server: nginx/1.10.0
Date: Sat, 07 May 2016 21:25:23 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: CraftSessionId=xxxxx; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Powered-By: Craft CMS
charset: utf-8
`

```
<full html of page>
```

Have you tried the cli with node v6?

**Comment by bezoerb** [comment] 2016-05-07 21:31
yes, but i have an apache running. I'll see if i can set up an nginx and try again.

**Comment by bezoerb** [comment] 2016-05-07 22:17
with nginx everything is fine, too.
Please enable debug and run again:
`export DEBUG='critical:*' && node_modules/.bin/critical http://dev.lovindublin.com/ -m`
Maybe this helps locating the error

**Comment by bezoerb** [comment] 2016-05-07 22:19
If this doesn't help i would add some additional debug logs in a separate branch until we can nail down the cause of the 403

**Comment by miralize** [comment] 2016-05-08 00:12
I think I found the issue for me at least. I use a font service from typography.com and they redirect a css file to a local css file. It seems the css wont follow redirects
		`<link href="//cloud.typography.com/6020032/784002/css/fonts.css" rel='stylesheet' />`

**Comment by pocketjoso** [comment] 2016-05-08 19:23
`typography.com` don't allow scraping of their stylesheets due to their licensing.

I presume `critical` needs to be updated to handle this. My own quick and dirty solution for the same problem for another project:
```
fetch(urlThatMightReturn403)
...
.catch(function (e) {
    if (e.message.toLowerCase() === 'forbidden') {
      console.log('ignoring forbidden css', cssUrl)
      return ''
    }
```

**Comment by bezoerb** [comment] 2016-05-08 21:19
@miralize, @mikeebee 
I've added a fix for this issue. Could you please check again using the `master` branch?
Thanks @pocketjoso :)

**Comment by miralize** [comment] 2016-05-08 22:24
Yes this works thanks @bezoerb ! 🍻

**Comment by mikeebee** [comment] 2016-05-13 01:38
@bezoerb sorry to be a simpleton but how do I use the master branch? The npm package doesn't seem to have changed.

**Comment by miralize** [comment] 2016-05-13 01:50
@mikeebee Change the line in your package.json where critical is set to `"critical": "addyosmani/critical#a4eea4bd41c547d00acaf31e4412c6e58d25308f",`

**Comment by mikeebee** [comment] 2016-05-13 02:56
@miralize thanks!

Ok, it now appears to be ignoring the page I pointed it at. Also, I'm getting these errors...

```
[12:52:27] Starting 'critical'...
Ignoring http://localurl.dev/ (403 Forbidden)
Ignoring http://localurl.dev/ (403 Forbidden)
Ignoring http://localurl.dev/ (403 Forbidden)
Unhandled rejection TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:339:9)
    at module.exports (projectdir/node_modules/penthouse/lib/index.js:67:8)
    at tryCatcher (projectdir/node_modules/critical/node_modules/bluebird/js/release/util.js:16:23)
    at ret (eval at <anonymous> (projectdir/node_modules/critical/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at projectdir/node_modules/critical/lib/core.js:155:24
    at run (projectdir/node_modules/core-js/modules/es6.promise.js:104:47)
    at projectdir/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/Users/mike/Sites/the-australian-ballet/node_modules/core-js/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by bezoerb** [comment] 2016-05-13 04:50
@mikeebee can you check the availability of `http://localurl.dev/` using curl?
```bash
curl http://localurl.dev/
```

**Comment by mikeebee** [comment] 2016-05-13 05:08
Yeah, all good. Took 8 seconds.

**Comment by bezoerb** [comment] 2016-05-16 21:12
Hmm,... it's hard to guess why critical get's an 403 while trying to fetch the page. Could you give some more insights on your setup?

**Comment by mikeebee** [comment] 2016-05-18 05:57
Sure thing, what info would be helpful?

**Comment by bezoerb** [comment] 2018-11-30 22:47
Closing this as nothing happened in the last 2 years ;)

Think this should be way better with the next version. The prerelease version can be installed with `npm i critical@next`

Feel free to reopen if the issue still exists.

**Closed by bezoerb** 2018-11-30 22:47 UTC
